### ISSUE TITLE
Thirteen Unhinged promos marked as originals, not reprints

### ISSUE THREAD

**Issue by doppeldeveloper** [scryfall/feedback#605] opened 2017-11-19 15:15 UTC
When searching [`e:unh -is:reprint`](https://scryfall.com/search?as=checklist&q=e%3Aunh+-is%3Areprint) multiple foil promos will come up, because the promo is considered the original, and the original is considered the reprint. You can see them in this list since they have the ★ symbol in the number column.

As a corollary there is [the list of UNH reprints (basic lands excluded)](https://scryfall.com/search?q=e%3Aunh+is%3Areprint+-t%3Abasic&as=checklist), all of which should be promos.

Incidentally none of these foil cards seem to show up under `is:promo`.

**Comment by Sniffnoy** [comment] 2017-11-19 21:06
This seems to be related to my #605.

Tangentially, not really related, but I wrote this in another one which was since closed and hasn't been addressed: Sword of Dungeons & Dragons has the HasCon version listed as the original, rather than the Unstable version.  Obviously it was chronologically first, but normally you guys don't consider promos to be originals (when a non-promo version exists), right?

**Comment by doppeldeveloper** [comment] 2017-11-20 00:33
Normally that's because the "original" exists in a set, and promos come after the fact or somehow "in advance" — like Zurgo's earlier appearance in a duel deck doesn't make his KTK set appearance not the proper original.

In Sword of D&D's case, the promo really is the original. It was created (from an outside perspective at least) as a promotional piece celebrating Hasbro products. But it's also showing up in Unstable. That's really unusual, but MTG breaks its own trends with regularity.

**Comment by csuhta** [comment] 2017-11-20 02:20
Fixed (for all sets):
- https://scryfall.com/search?q=%2B%2Be%3Aunh+is%3Areprint
- https://scryfall.com/search?q=%2B%2Be%3Aunh+not%3Areprint

@Sniffnoy I'm stumped on your question. It's unclear if the HasCon promos (which were sold as a "box" of "promos" contain the original print for Sword). Because the set also contains other original cards, I'm leaning toward H17 being the original source of the card, but we're looking for someone good to ask adjacent to WoTC

**Comment by Sniffnoy** [comment] 2017-11-20 02:23
Ha, I totally mistook you for a Scryfall person! I'm pretty sure it was designed for Unstable first, seeing how far in advance Unstable was done; I think it's exactly analogous to the duel deck case.  If like there was a multi-year gap between them, that would be one thing -- like, Eighth Edition is clearly not the original for Giant Badger! -- but, well, there wasn't; they were really close together.  (And I'm pretty sure I remember Mark Rosewater talking somewhere -- maybe on his podcast? -- about designing that particular card for Unstable.)

**Comment by silasary** [comment] 2017-11-20 02:36
According to these, Maro seems to be claiming H17 was a promo, and UST is the original printing.
http://markrosewater.tumblr.com/post/165441004738/last-year-you-said-we-hadnt-seen-your-favorite
http://markrosewater.tumblr.com/post/163567568323/im-very-sad-ill-never-get-to-cast-nerf-war-as-it

Which would make Nerf War and Grimlock the first non-reprint promos since Nalathni Dragon (or maybe Gleemox)

**Comment by csuhta** [comment] 2017-11-20 03:44
Ok, that makes sense. Closing this issue, the chicken-egg promo problem is tracked in #188

**Closed by csuhta** 2017-11-20 03:44 UTC
