### ISSUE TITLE
First character of oracle text not copiable when manamoji.

### ISSUE THREAD

**Issue by chuckharmston** [scryfall/feedback#202] opened 2017-08-07 14:47 UTC
Feedback from [@TheProxyGuy](https://twitter.com/TheProxyGuy):

When the first character of a card's oracle box is a manamoji, its text is not copiable. Perhaps adding a zero-width character before the start of the text would help this?

**Comment by csuhta** [comment] 2017-08-07 18:27
I don't have this problem: https://csuhta.s3.amazonaws.com/s/AWbXyZtJ.mp4

Perhaps it's browser/OS specific?

**Comment by josephprice** [comment] 2017-08-07 19:43
I can't reproduce on Mac / Chrome. Used:
https://scryfall.com/card/m12/105

**Comment by csuhta** [comment] 2017-10-07 08:31
Closing because of age and failure to reproduce this issue

**Closed by csuhta** 2017-10-07 08:31 UTC
