### ISSUE TITLE
Link to tokens made by card on card page

### ISSUE THREAD

**Issue by Subbarker** [scryfall/feedback#492] opened 2017-10-19 17:37 UTC
For instance, on the page for [Legion's Landing](https://scryfall.com/card/xln/22), link to [the vampire token from Ixalan ](https://scryfall.com/card/txln/1)

**Comment by Subbarker** [comment] 2017-10-19 18:24
It seems like this is intended looking at the section: "FACES, TOKENS, & OTHER PARTS" on [some cards](https://scryfall.com/card/emn/15a).

**Comment by csuhta** [comment] 2017-10-19 21:49
Duplicate of #203

**Closed by csuhta** 2017-10-19 21:49 UTC
